# -*- coding: utf-8 -*-
"""LeetcodeDS_HashTable_GroupAnagrams.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14XNtBujf9B0FNOAeIazOhGQ7W5ikOb4Z

###Hash Table 之 Group Anagrams

*Anagrams 是指異構詞, 例如eat ~ ate ~tea
- 任務描述:
把所有的Anagrams都分成一組
"""

class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        hashtable=defaultdict(list)
        #要用defaultdict(list), 因為單純的{}不會auto添加新的key
        #list: 这样当访问不存在的键时，它会自动创建一个空列表。
        for word in strs:
            sorted_word=''.join(sorted(word))
            hashtable[sorted_word].append(word) #append 本身就是list 在append
        return list(hashtable.values())